### ISSUE TITLE
Sass / SCSS

### ISSUE THREAD

**Issue by ericltw** [ericltw/notes#47]

**Comment by ericltw** [comment]
### SCSS

- 介紹

  Sass是一種style sheet language，也是preprocessor scripting language，經過interprete後生成CSS。因此SaSS的目的並非取代CSS，而是在兼容CSS，在CSS之上提供額外的feature，如: variable, nesting, mixins, selector inheriance。

  而在SaSS中包含兩種語法，分別為SCSS與indented syntax（因副檔名為.sass，所以有時也被稱為"Sass"）。



### Syntax

- Overview

  - SCSS

    附檔名為.scss，為CSS的超集，因此所有有效的CSS均是有效的SCSS。

  - The indented syntax

    Indented syntax提供與SCSS相同的feature，與SCSS的差異為，indented syntax使用縮進，而不是大括號與分號的格式。

- Structure of stylesheet

  就像CSS，大多數的Sass stylesheets主要由屬性聲明的規則所組成，但Sass擁有與這些樣式共存的功能，這些功能分為可以份為兩大類，分別為statement與expression。

  - Statement

    Sass由一系列statements所組成，Sass processor根據statements進行評估後，構建CSS。

  - Expression

    Expression是位於屬性或聲明變量右側的任何內容，expression的特性為，每個expression均會生成一個值，任何有效的CSS property也是Sass expressions。其中expression可分為三大類，literals, operations, other expression。

  > 關於Statements與Expressions的細節內容，參考https://sass-lang.com/documentation/syntax/structure。



### Style Rules

- Overview

  Style rules是Sass的基礎，與CSS的工作方式相同，element選擇使用與selector關聯，該element就會根據selector所設置的屬性呈現element的外觀。

  - General

    ````scss
    .button {
        padding: 3px 10px;
        font-size: 12px;
    }
    ````

  - Nesting

    Sass避免需要重複相同的selector，因此引入Nesting的概念，能夠在一個style rule中編寫令一個style rule，Sass將會合併外部selector與內部selector。

    ````scss
    nav {
        ul {
            margin: 0;
            padding: 0;
        }
    }
    ````

  - Interpolation

    透過interpolation，能夠將expression(如：variable)，注入至selector。

    ````scss
    ＠mixin define-emoji($name, $glyph) {
        span.emoji-#{$name} {
            font-family: 
        }
    }
    ````

- Property Declarations

  property declarations定義了當一個element與selector關聯後，element的style。一個declaration的值可以是任何Sass expression。

  > https://sass-lang.com/documentation/style-rules/declarations

- Parent selector

  parent selector &用於nested selectors，＆引用了外部的selector。

  ````scss
  .alert {
      &:hover {
          font-size: bold;
      }
  }
  ````

- Placeholder selectors

  placeholder select是一種特殊的selector，看似class selector，以%開頭，並不會包含在CSS的輸出中，但能夠與extend一同使用。

  ````scss
  %toolbelt {
      box-sizing: border-box;
  }
  
  .action-buttons {
      @extend %toolbelt;
      color: green;
  }
  ````

  

### Variables

以$開頭的名稱分配一個值，就可以引用該變數的名稱，而非值的本身。

> 與CSS的variable之間存在差異。

````scss
$variable: 1;

.rule-1 {
    value: $variable;
}
````



### Interpolation

interpolation幾乎可以在Sass stylesheet的任何地方使用，以嵌入expression的結果。

````scss
@mixin corner-icon($name) {
    .icon-#{$name} {
        background-image: url("/icons/#{$name}.svg");
    }
}

@include corner-icon("mail");
````



### At-rules

在CSS的at-rules之上，Sass添加了許多額外的at-rules。

- @import

  擴展CSS @import規則，能夠import Sass和CSS stylesheet，提供mixins, functions, variables的access。 

- @mixin / @include

  你定義可以在整個stylesheet中重複使用的style。

- @function

  對Value進行複雜的操作，並且能夠在整個stylesheet中重複使用。

- @extend

  當一個class具有另一個class的所有style時，

- @at-root

- @error

- @warn

- @debug

- flow control

  - @if / @else
  - @each
  - @for
  - @while





### Values

- Numbers

  Number分為兩個部份，分別為number和unit。

- Strings

  String支持兩種內部結構相同，但呈現方式不同的字串，分別為quoted strings(e.g. "Helvetica Neue")，與unquoted strings(e.g. bold)。

- Colors

- Lists

  List是包含多個值得序列。在Sass中，list可以透過,分開，或是空格，只要在列表中保持一致即可。且在Sass中，list不一定需要特殊的括號。

- Maps

  在Sass中，map包含成對的key和value，並通過相應的key找到value。表示為（expression: expression, expression: expression）。與list不同，map需要加上括號。

- true / false

- null

- Functions
